In [2]:
import numpy as np
size = 50
A = np.random.randn(size)
B = np.random.randn(size)
C = A + B
print("The maximum is: %.2f" % C.max())
print("The minimum is: %.2f" % C.min())
print("The sum is: %.2f" % C.sum())
print("The mean is: %.2f" % C.mean())
print("The number of negative values is:",np.where(C < 0, 1, 0).sum())

The maximum is: 3.29
The minimum is: -3.60
The sum is: 0.27
The mean is: 0.01
The number of negative values is: 26


In [4]:
A = np.random.randn(5,4)
print("The original matrix:\n", A)

print("The maximum values for each row:",A.max(axis=1))
print("The maximum values for each column:",A.max(axis=0))
print("The minimum values for each row:",A.min(axis=1))
print("The minimum values for each column:",A.min(axis=0))
print("The sub-matrix: \n", A[2:,1:])


The original matrix:
 [[-0.09764845 -1.15705135 -0.71550696 -1.2846392 ]
 [-1.4865479   1.39829876  1.35081742  1.22765508]
 [-0.23998051  0.30636594 -1.03882608  0.55984706]
 [-2.16863294 -0.41750988 -0.6951534   0.77379974]
 [ 0.33089574 -1.35020222 -1.04544839  1.47090285]]
The maximum values for each row: [-0.09764845  1.39829876  0.55984706  0.77379974  1.47090285]
The maximum values for each column: [0.33089574 1.39829876 1.35081742 1.47090285]
The minimum values for each row: [-1.2846392  -1.4865479  -1.03882608 -2.16863294 -1.35020222]
The minimum values for each column: [-2.16863294 -1.35020222 -1.04544839 -1.2846392 ]
The sub-matrix: 
 [[ 0.30636594 -1.03882608  0.55984706]
 [-0.41750988 -0.6951534   0.77379974]
 [-1.35020222 -1.04544839  1.47090285]]


In [10]:
A = np.random.randn(10,10)
print("The sum of all the positive values is %.2f" %(A * (A>0)).sum())
print("The sum of all the negative values is %.2f" % (A * (A<0)).sum())

The sum of all the positive values is 46.52
The sum of all the negative values is -37.17
